Game = ""
TmxGame = ""
BindIP = ""
XmlRpcPort = 5112
AutoSkipMode = "AuthorMedal"
TimeLimit = 3600000

Preset = ""

ServerName = "$$0BFRandomizer $$FF80.1.0"
GameSettings = "MatchSettings/Randomizer.txt"

WelcomeMessage = '''
$FF0Welcome to $s$0BFRandomizer $FF8Anywhere$FF0!
Once you're ready, type $FF0/start
To skip a challenge, type $FF0/skip
To ban a challenge from appearing again, type $FF0/imp
'''

[DownloadUrls]
TMF = "http://files2.trackmaniaforever.com/TrackmaniaServer_2011-02-21.zip"
TM = "http://slig.free.fr/TM/dedicated/TmDedicatedServer_2006-05-30.zip"

[TmxQuery]
primarytype = 0