Game = ""
TmxGame = ""
BindIP = ""
XmlRpcPort = 5112
AutoSkipMode = "AuthorMedal"
TimeLimit = 3600000

Preset = ""

ServerName = "Randomizer Anywhere"
GameSettings = "MatchSettings/Randomizer.txt"

WelcomeMessage = '''
$FF0Welcome to $s$0BFRandomizer $FF8Anywhere$FF0!
To pick a preset, see $FF0/presets
Once you're ready, type $FF0/start
To skip a map, type $FF0/skip
'''

[DownloadUrls]
TMF = "http://files2.trackmaniaforever.com/TrackmaniaServer_2011-02-21.zip"
TM = "http://slig.free.fr/TM/dedicated/TmDedicatedServer_2006-05-30.zip"

[TmxQuery]
primarytype = 0